### ISSUE TITLE
[Upstream]: LND 0.15.3

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/service-pipeline#28] opened 2022-07-14 22:40 UTC
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/63
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/59
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/54
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/41
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/36 [IN PROGRESS]

**Comment by kn0wmad** [comment] 2022-08-10 15:51
Dupe of #29?

**Comment by kn0wmad** [comment] 2022-08-10 21:09
I noticed that.  I'm confused why there are 2 updates?

**Comment by chrisguida** [comment] 2022-08-10 23:04
Because it's impossible to get all of the above done in time for the 0.15.0 release

**Comment by chrisguida** [comment] 2022-09-21 18:31
Assigning to @islandbitcoin

**Comment by chrisguida** [comment] 2022-09-21 18:34
I'll finish the js properties conversion, doesn't need to go with 0.15.1

**Closed** 2024-04-05 03:11 UTC
